import tailwindcss from "@tailwindcss/vite";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: false },
  
  modules: [
    "@nuxt/content",
    "@nuxt/eslint",
    "@nuxt/icon",
    "@nuxtjs/i18n",
    "@nuxtjs/seo",
    "@nuxtjs/sitemap",
    "@nuxtjs/robots",
    "nuxt-og-image",
  ],
  
  // Site configuration for SEO
  site: {
    url: "https://aboubak.art",
    name: "Aboubakar Sidik Faha | DevOps & Software Architect",
    description: "DevOps Engineer & Software Architect based in Abidjan, Ivory Coast. Transforming digital visions into reality with innovative cloud, DevOps, and AI solutions.",
    defaultLocale: "en",
    indexable: true,
  },
  
  vite: {
    plugins: [tailwindcss()],
    css: {
      devSourcemap: false
    },
    build: {
      sourcemap: false,
      cssMinify: true,
      minify: 'terser',
    }
  },
  
  css: ["~/assets/css/tailwind.css"],
  
  i18n: {
    locales: [
      { code: 'en', name: 'English', file: 'en.json', iso: 'en-US' },
      { code: 'fr', name: 'Français', file: 'fr.json', iso: 'fr-FR' }
    ],
    defaultLocale: 'en',
    langDir: 'locales',
    strategy: 'prefix_except_default',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',
    },
    baseUrl: 'https://aboubak.art',
  },
  
  content: {
    renderer: {
      anchorLinks: false
    }
  },

  // SEO Module configuration
  seo: {
    // Automatic SEO features
    redirectToCanonicalSiteUrl: true,
    fallbackTitle: false,
    automaticDefaults: true,
  },
  
  // OG Image configuration
  ogImage: {
    defaults: {
      component: 'DefaultOgImage',
      renderer: 'satori',
    },
    // Use system fonts to avoid font download issues
    fonts: [],
    // Don't include custom fonts in the bundle, use system fonts
    runtimeCacheStorage: true,
  },
  
  // Sitemap configuration
  sitemap: {
    enabled: true,
    autoI18n: true,
    exclude: ['/error', '/_nuxt/**'],
    defaults: {
      priority: 0.7,
      changefreq: 'weekly',
    }
  },
  
  // Robots configuration
  robots: {
    enabled: true,
    allow: ['/'],
    disallow: ['/error', '/_nuxt'],
    sitemap: 'https://aboubak.art/sitemap.xml',
  },

  app: {
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1, maximum-scale=5',
      titleTemplate: '%s %separator %siteName',
      templateParams: {
        separator: '|',
        siteName: 'Aboubakar Sidik Faha',
      },
      meta: [
        // Primary Meta Tags
        { name: 'description', content: 'DevOps Engineer & Software Architect based in Abidjan, Ivory Coast. Transforming digital visions into reality with innovative cloud, DevOps, and AI solutions.' },
        { name: 'keywords', content: 'DevOps, Software Architect, Cloud Architecture, AWS, Azure, Kubernetes, Docker, CI/CD, Abidjan, Ivory Coast, Freelance Developer, AI, Machine Learning' },
        { name: 'author', content: 'Aboubakar Sidik Faha' },
        { name: 'robots', content: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' },
        
        // Open Graph / Facebook
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Aboubakar Sidik Faha' },
        { property: 'og:locale', content: 'en_US' },
        { property: 'og:locale:alternate', content: 'fr_FR' },
        // Note: og:image is auto-generated by nuxt-og-image
        
        // Twitter
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:site', content: '@sidikfaha' },
        { name: 'twitter:creator', content: '@sidikfaha' },
        // Note: twitter:image is auto-generated by nuxt-og-image
        
        // Mobile & PWA
        { name: 'theme-color', content: '#3b82f6' },
        { name: 'msapplication-TileColor', content: '#3b82f6' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
        
        // Verification (placeholder - update with actual values)
        // { name: 'google-site-verification', content: 'YOUR_VERIFICATION_CODE' },
      ],
      link: [
        // Preconnect for performance
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        
        // DNS Prefetch for external resources
        { rel: 'dns-prefetch', href: 'https://images.unsplash.com' },
        
        // Favicon and icons
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
        { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
        { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' },
        
        // Web App Manifest
        { rel: 'manifest', href: '/site.webmanifest' },
        
        // Fonts with display=swap for performance
        { 
          rel: 'stylesheet', 
          href: 'https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;500;700&family=Inter:wght@300;400;500;600;700;800;900&display=swap',
          media: 'print',
          onload: "this.media='all'"
        },
      ],
      htmlAttrs: {
        lang: 'en',
        dir: 'ltr',
      },
      bodyAttrs: {
        class: 'antialiased',
      },
    },
  },
  
  // Build optimization for performance
  nitro: {
    prerender: {
      routes: ['/sitemap.xml', '/robots.txt'],
      crawlLinks: true,
      failOnError: false,
    },
    compressPublicAssets: true,
    minify: true,
  },
  
  // Experimental features for better performance
  experimental: {
    payloadExtraction: true,
    renderJsonPayloads: true,
    typedPages: true,
  },
  
  // Features for SEO
  features: {
    inlineStyles: false,
  },
});
